# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.16
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: brian.whippo@algorand.foundation
author_name: Brian Whippo
cloud_provider: netlify
contract_name: de_chametz
deployment_language: python
preset_name: production
project_name: deChametzMe

