[algokit]
min_version = "v2.0.0"

[project]
type = "frontend"
name = 'DeChametzMe-frontend'
artifacts = "src/contracts"

[project.run]
build = { commands = ['pnpm run build'], description = 'Build frontend' }
test = { commands = ['pnpm run test'], description = 'Run frontend tests' }
lint = { commands = ['pnpm run lint'], description = 'Lint frontend code' }
ci-deploy-netlify = { commands = [
    'npm install --global netlify-cli@latest',
    'netlify login',
    'netlify deploy --build --prod'
  ], description = 'Deploy to Netlify' }
