# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.13
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: brian.whippo@algorand.foundation
author_name: Brian Whippo
cloud_provider: netlify
preset_name: production
project_name: DeChametzMe-frontend
