# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: brian.whippo@algorand.foundation
author_name: Brian Whippo
contract_name: de_chametz
deployment_language: python
preset_name: production
project_name: DeChametzMe-contracts
