name: Validate DeChametzMe-frontend

on:
  workflow_call:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./projects/DeChametzMe-frontend/

    steps:
      - name: List repository files
        run: ls -la /home/runner/work/DeChametzMe/DeChametzMe

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install algokit
        run: pipx install algokit

      - name: Install dependencies
        run: algokit project bootstrap all --project-name 'DeChametzMe-frontend'

      - name: Run linters
        run: algokit project run lint --project-name 'DeChametzMe-frontend'

      - name: Run unit tests
        run: algokit project run test --project-name 'DeChametzMe-frontend'

      - name: Build
        run: algokit project run build --project-name 'DeChametzMe-frontend'
